Data_Full:
  name: "Data"
  datasets:
    - Muon0_Run2025B_v1
    - Muon0_Run2025C_v1
    - Muon0_Run2025C_v2
    - Muon0_Run2025D_v1
    - Muon0_Run2025E_v1
    - Muon0_Run2025F_v1
    - Muon0_Run2025F_v2
    - Muon0_Run2025G_v1
    - Muon1_Run2025B_v1
    - Muon1_Run2025C_v1
    - Muon1_Run2025C_v2
    - Muon1_Run2025D_v1
    - Muon1_Run2025E_v1
    - Muon1_Run2025F_v1
    - Muon1_Run2025F_v2
    - Muon1_Run2025G_v1
    - MuonEG_Run2025B_v1
    - MuonEG_Run2025C_v1
    - MuonEG_Run2025C_v2
    - MuonEG_Run2025D_v1
    - MuonEG_Run2025E_v1
    - MuonEG_Run2025F_v1
    - MuonEG_Run2025F_v2
    - MuonEG_Run2025G_v1

Data_EGamma:
  name: "Data EGamma"
  datasets:
    - EGamma0_Run2025B_v1
    - EGamma0_Run2025C_v1
    - EGamma0_Run2025C_v2
    - EGamma0_Run2025D_v1
    - EGamma0_Run2025E_v1
    - EGamma0_Run2025F_v1
    - EGamma0_Run2025F_v2
    - EGamma0_Run2025G_v1
    - EGamma1_Run2025B_v1
    - EGamma1_Run2025C_v1
    - EGamma1_Run2025C_v2
    - EGamma1_Run2025D_v1
    - EGamma1_Run2025E_v1
    - EGamma1_Run2025F_v1
    - EGamma1_Run2025F_v2
    - EGamma1_Run2025G_v1
    - EGamma2_Run2025B_v1
    - EGamma2_Run2025C_v1
    - EGamma2_Run2025C_v2
    - EGamma2_Run2025D_v1
    - EGamma2_Run2025E_v1
    - EGamma2_Run2025F_v1
    - EGamma2_Run2025F_v2
    - EGamma2_Run2025G_v1
    - EGamma3_Run2025B_v1
    - EGamma3_Run2025C_v1
    - EGamma3_Run2025C_v2
    - EGamma3_Run2025D_v1
    - EGamma3_Run2025E_v1
    - EGamma3_Run2025F_v1
    - EGamma3_Run2025F_v2
    - EGamma3_Run2025G_v1

Data_Muon:
  name: "Data Muon"
  datasets:
    - Muon0_Run2025B_v1
    - Muon0_Run2025C_v1
    - Muon0_Run2025C_v2
    - Muon0_Run2025D_v1
    - Muon0_Run2025E_v1
    - Muon0_Run2025F_v1
    - Muon0_Run2025F_v2
    - Muon0_Run2025G_v1
    - Muon1_Run2025B_v1
    - Muon1_Run2025C_v1
    - Muon1_Run2025C_v2
    - Muon1_Run2025D_v1
    - Muon1_Run2025E_v1
    - Muon1_Run2025F_v1
    - Muon1_Run2025F_v2
    - Muon1_Run2025G_v1

Data_MuonEG:
  name: "Data MuonEG"
  datasets:
    - MuonEG_Run2025B_v1
    - MuonEG_Run2025C_v1
    - MuonEG_Run2025C_v2
    - MuonEG_Run2025D_v1
    - MuonEG_Run2025E_v1
    - MuonEG_Run2025F_v1
    - MuonEG_Run2025F_v2
    - MuonEG_Run2025G_v1


custom_CI_background:
  name: "CI -- Background"
  color: "kGreen-3"
  datasets: [ ]

custom_CI_signal:
  name: "CI -- signals"
  color: "kAzure+10"
  datasets: [ ]

custom_CI_data:
  name: "CI -- data"
  color: "kAzure+10"
  datasets:
    - Muon0_Run2025B_v1
