authorized_users:
  - kandrosov
  - valeriadamante
  - acyeagle

expected_headers:
  - "@cms-flaf-bot test"
  - "@cms-flaf-bot please test"
  - "[@cms-flaf-bot](https://github.com/cms-flaf-bot) test"
  - "[@cms-flaf-bot](https://github.com/cms-flaf-bot) please test"

variables:
  HH_bbWW_version: "main"
  HH_bbtautau_version: "main"
  H_mumu_version: "main"
  FLAF_version: "default"
  Corrections_version: "default"
  HH_bbWW_active: "0"
  HH_bbtautau_active: "0"
  H_mumu_active: "1"
  HH_bbWW_task: "FLAF.Analysis.tasks.HistPlotTask"
  HH_bbtautau_task: "FLAF.Analysis.tasks.HistPlotTask"
  H_mumu_task: "FLAF.Analysis.tasks.HistPlotTask"
  HH_bbWW_dataset: "GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_350"
  HH_bbtautau_dataset: "GluGlutoHHto2B2Tau_kl_1p00_kt_1p00_c2_0p00"
  H_mumu_dataset: "VBFHto2Mu"

gitlab_url: "https://gitlab.cern.ch/api/v4/projects/210600/trigger/pipeline"
gitlab_branch: "master"
