python3 /afs/cern.ch/work/v/vdamante/H_mumu/Analysis/plotting_tools/main_plotter.py --inFile /eos/user/v/vdamante/H_mumu/merged_hists/mumu_resolution_BS_ScaRe/Run3_2022/m_mumu_resolution/m_mumu_resolution.root  --outFile prova_2022 --var m_mumu_resolution --period Run3_2022 --region Z_sideband --category baseline_muonJet --contribution GluGluHto2Mu --compare_list leading_mu_pt_45to52_etainclusive,leading_mu_pt_45to52_BB,leading_mu_pt_45to52_etainclusive,leading_mu_pt_45to52_BB,leading_mu_pt_45to52_BO,leading_mu_pt_45to52_BE,leading_mu_pt_45to52_OB,leading_mu_pt_45to52_OO,leading_mu_pt_45to52_OE,leading_mu_pt_45to52_EB,leading_mu_pt_45to52_EO,leading_mu_pt_45to52_EE --rebin


python3 /afs/cern.ch/work/v/vdamante/H_mumu/Analysis/plotting_tools/main_plotter.py --inFile /eos/user/v/vdamante/H_mumu/merged_hists/mumu_resolution_BS_ScaRe/Run3_2023/m_mumu_resolution/m_mumu_resolution.root  --outFile prova_2023 --var m_mumu_resolution --period Run3_2023 --region Z_sideband --category baseline_muonJet --contribution GluGluHto2Mu --compare_list leading_mu_pt_45to52_etainclusive,leading_mu_pt_45to52_BB,leading_mu_pt_45to52_etainclusive,leading_mu_pt_45to52_BB,leading_mu_pt_45to52_BO,leading_mu_pt_45to52_BE,leading_mu_pt_45to52_OB,leading_mu_pt_45to52_OO,leading_mu_pt_45to52_OE,leading_mu_pt_45to52_EB,leading_mu_pt_45to52_EO,leading_mu_pt_45to52_EE --rebin


python3 /afs/cern.ch/work/v/vdamante/H_mumu/Analysis/plotting_tools/main_plotter.py --inFile /eos/user/v/vdamante/H_mumu/merged_hists/mumu_resolution_BS_ScaRe/Run3_2022/m_mumu_resolution/m_mumu_resolution.root  --outFile prova_2022 --var m_mumu_resolution --period Run3_2022 --region Z_sideband --category baseline_muonJet --contribution GluGluHto2Mu --compare_list inclusive_etainclusive,inclusive_BB,inclusive_etainclusive,inclusive_BB,inclusive_BO,inclusive_BE,inclusive_OB,inclusive_OO,inclusive_OE,inclusive_EB,inclusive_EO,inclusive_EE --rebin


leading_mu_pt_45to52_etainclusive,leading_mu_pt_45to52_BB,leading_mu_pt_45to52_etainclusive,leading_mu_pt_45to52_BB,leading_mu_pt_45to52_BO,leading_mu_pt_45to52_BE,leading_mu_pt_45to52_OB,leading_mu_pt_45to52_OO,leading_mu_pt_45to52_OE,leading_mu_pt_45to52_EB,leading_mu_pt_45to52_EO,leading_mu_pt_45to52_EE --rebin



for ptCat in inclusive leading_mu_pt_upto26 leading_mu_pt_26to45 leading_mu_pt_upto45 leading_mu_pt_45to52 leading_mu_pt_52to62 leading_mu_pt_above62 ; do for period in  2022 2022EE 2023 2023BPix; do sh /afs/cern.ch/work/v/vdamante/H_mumu/Analysis/plotting_tools/scripts/plot_private_or_web.sh mumu_resolution_BS_ScaRe ${period} mumu_resolution_BS_ScaRe_${ptCat} "mass_inclusive Z_sideband" "baseline_muonJet" 0 "--compare_list ${ptCat}_etainclusive,${ptCat}_BB,${ptCat}_BO,${ptCat}_BE,${ptCat}_OB,${ptCat}_OO,${ptCat}_OE,${ptCat}_EB,${ptCat}_EO,${ptCat}_EE --rebin" ; done; done
