WWto2L2Nu_powheg = [1]
WWto4Q_powheg = [1]
WWtoLNu2Q_powheg = [1]

WZto2L2Q_powheg = [1]
WZto3LNu_powheg = [1]
WZtoLNu2Q_powheg = [1]

ZZto2L2Nu_powheg = [1]
ZZto2L2Q_powheg = [1]
ZZto2Nu2Q_powheg = [1]
ZZto4L_powheg = [1]

TTto2L2Nu = [1]
TTto4Q = [1]
TTtoLNu2Q = [1]

DYto2L_M_10to50_amcatnloFXFX = [3]
DYto2L_M_50_amcatnloFXFX = [3]

DYto2Mu_MLL_105to160_amcatnloFXFX = [3]

DYto2Mu_MLL_120to200_powheg = [3]
DYto2Mu_MLL_200to400_powheg = [3]
DYto2Mu_MLL_50to120_powheg = [3]

GluGluHto2Mu = [1]
VBFHto2Mu = [1]

LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole = [4]
LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_ext1 = [4]
LLJJ_SM_M-50_MJJ120_13p6TeV_dipole = [4]
LLJJ_SM_M-50_MJJ120_13p6TeV_dipole_ext1 = [4]