
for region in mass_inclusive Z_sideband H_sideband
    do for cat in ggH VBF_JetVeto baseline VBF ;
        do mkdir -p /eos/user/v/vdamante/www/H_mumu/plots/Run3_2022/26Aug/${region}/${cat} ;
        cp /eos/user/v/vdamante/www/H_mumu/index.php /eos/user/v/vdamante/www/H_mumu/plots/Run3_2022/26Aug/${region}/${cat}/ ;
        cp /eos/user/v/vdamante/www/H_mumu/Parsedown.php /eos/user/v/vdamante/www/H_mumu/plots/Run3_2022/26Aug/${region}/${cat}/ ;
        for var in cosTheta_CS m_mumu_BS mu1_eta mu2_bsConstrainedPt mu2_pt  pt_mumu  y_mumu dR_mumu m_mumu_BS_ScaRe  mu1_phi mu2_BS_pt_1_corr  mu2_pt_nano pt_mumu_BS eta_mumu  m_mumu_nano mu1_bsConstrainedPt mu1_pt  mu2_eta phi_CS  pt_mumu_BS_ScaRe m_mumu  mu1_BS_pt_1_corr  mu1_pt_nano mu2_phi phi_mumu pt_mumu_nano ;
        do
            echo python3 Analysis/plotting_tools/main_plotter.py --inFile /eos/user/v/vdamante/H_mumu/merged_hists/Run3_2022/26Aug2025/${var}/${var}_Central.root --outFile /eos/user/v/vdamante/www/H_mumu/plots/Run3_2022/26Aug/${region}/${cat}/${var}_LogY_Sig --var ${var} --period Run3_2022 --mass_region ${region} --category ${cat} --contribution all --rebin --wantLogY --wantSignal --wantData --wantRatio ;
            # python3 Analysis/plotting_tools/main_plotter.py --inFile /eos/user/v/vdamante/H_mumu/merged_hists/Run3_2022/26Aug2025/${var}/${var}_Central.root --outFile /eos/user/v/vdamante/www/H_mumu/plots/Run3_2022/26Aug/${region}/${cat}/${var}_LogY_Sig --var ${var} --period Run3_2022 --mass_region ${region} --category ${cat} --contribution all --rebin --wantLogY --wantSignal --wantData --wantRatio ;
            # echo python3 Analysis/plotting_tools/main_plotter.py --inFile /eos/user/v/vdamante/H_mumu/merged_hists/Run3_2022/26Aug2025/${var}/${var}_Central.root --outFile /eos/user/v/vdamante/www/H_mumu/plots/Run3_2022/26Aug/${region}/${cat}/${var}_Sig --var ${var} --period Run3_2022 --mass_region ${region} --category ${cat} --contribution all --rebin --wantSignal --wantData --wantRatio ;
            # python3 Analysis/plotting_tools/main_plotter.py --inFile /eos/user/v/vdamante/H_mumu/merged_hists/Run3_2022/26Aug2025/${var}/${var}_Central.root --outFile /eos/user/v/vdamante/www/H_mumu/plots/Run3_2022/26Aug/${region}/${cat}/${var}_Sig --var ${var} --period Run3_2022 --mass_region ${region} --category ${cat} --contribution all --rebin --wantSignal --wantData --wantRatio ;
            # echo python3 Analysis/plotting_tools/main_plotter.py --inFile /eos/user/v/vdamante/H_mumu/merged_hists/Run3_2022/26Aug2025/${var}/${var}_Central.root --outFile /eos/user/v/vdamante/www/H_mumu/plots/Run3_2022/26Aug/${region}/${cat}/${var}_LogY_noSig --var ${var} --period Run3_2022 --mass_region ${region} --category ${cat} --contribution all --rebin --wantData --wantRatio --wantLogY ;
            # python3 Analysis/plotting_tools/main_plotter.py --inFile /eos/user/v/vdamante/H_mumu/merged_hists/Run3_2022/26Aug2025/${var}/${var}_Central.root --outFile /eos/user/v/vdamante/www/H_mumu/plots/Run3_2022/26Aug/${region}/${cat}/${var}_LogY_noSig --var ${var} --period Run3_2022 --mass_region ${region} --category ${cat} --contribution all --rebin --wantData --wantRatio --wantLogY ;
            # echo python3 Analysis/plotting_tools/main_plotter.py --inFile /eos/user/v/vdamante/H_mumu/merged_hists/Run3_2022/26Aug2025/${var}/${var}_Central.root --outFile /eos/user/v/vdamante/www/H_mumu/plots/Run3_2022/26Aug/${region}/${cat}/${var}_noSig --var ${var} --period Run3_2022 --mass_region ${region} --category ${cat} --contribution all --rebin --wantData --wantRatio ;
            # python3 Analysis/plotting_tools/main_plotter.py --inFile /eos/user/v/vdamante/H_mumu/merged_hists/Run3_2022/26Aug2025/${var}/${var}_Central.root --outFile /eos/user/v/vdamante/www/H_mumu/plots/Run3_2022/26Aug/${region}/${cat}/${var}_noSig --var ${var} --period Run3_2022 --mass_region ${region} --category ${cat} --contribution all --rebin --wantData --wantRatio ;
        done
    done
done
