name: Check repository state

on:
  pull_request:
    types: [ "opened", "synchronize", "reopened", "labeled" ]
    workflow_call:

permissions:
  contents: read
  checks: write

jobs:
  sanity-checks:
    uses: cms-flaf/FLAF/.github/workflows/repo-sanity-checks.yaml@main
    secrets: inherit
